title: CronosPro
description: > Опыт использования ИСУБД CronosPro, примеры наработок: проектирование форм ввода, программирование на Lua и языке формулч
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "/" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sinilga # add your name
author-img: "unnamed.png" # add your photo
about-author: Дата-инженер, специализируюсь на проектировании и ведении банков данных под управлением ИСУБД CronosPro. # add description
social-github: sinilga # add your Github handle
social-email: sinilga7@yandex.ru # add your Email address

# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
# social-linkedin: # add your Linkedin handle

# Disqus
# discus-identifier: Sinilga # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
